delete (ici_architecture.png): delete to replace
bonitasoft/bonita-ici-doc pull request #37
Opened 2018-10-02 15:39 UTC by NathalieC

2018-10-10 07:48 UTC, laurentleseigneur requested changes
needs some fix
additionally, we have dead links in deployed PR due to missing images

2018-10-10 07:48 UTC, laurentleseigneur commented on md/getting_started.md
> +* The BICI application: `ici-application-<version>.zip`
name has been changed to `bici-application-<version>.zip`

2018-10-10 07:48 UTC, laurentleseigneur commented on md/getting_started.md
> +* An installer: `bin/bonita-bici`
installer name is still `bonita-ici`

2018-10-10 07:48 UTC, laurentleseigneur commented on md/installation_guide.md
> +Run the Add-on using `bonita-bici` (`bonita-bici.bat` on Windows platform) script that is located inside the `bin` folder
installer are still  `bonita-ici` and `bonita-bici.bat`

2018-10-10 07:48 UTC, laurentleseigneur commented on md/installation_guide.md
> +It can be stopped using `bonita-bici stopStorage stopApp`
same as above

2018-10-10 07:48 UTC, laurentleseigneur commented on md/installation_guide.md
> +    |---- bin/bonita-bici                          // an utility that start the dockers and deploy L.A.s
same remark

2018-10-10 07:48 UTC, laurentleseigneur commented on md/installation_guide.md
> +    |---- bin/bonita-bici.bat                      // an utility that start the dockers and deploy L.A.s (Windows)
same remark

2018-10-10 07:48 UTC, laurentleseigneur commented on md/installation_guide.md
> +#bonita.bici.polling.profile=advanced
property has not been renamed

2018-10-10 07:48 UTC, laurentleseigneur commented on md/installation_guide.md
> +3. Edit the file `configuration.properties` to configure `bonita.bici.application.url`
still `bonita.ici.application.url`

2018-10-10 07:48 UTC, laurentleseigneur commented on md/installation_guide.md
> +3. Edit the file `configuration.properties` to configure `bonita.bici.application.url`
`bonita.ici.application.url`

2018-10-10 07:48 UTC, laurentleseigneur commented on md/polling.md
> +The polling can be handled on a page served directly on the BICI backend. By default it can be accessed on [http://localhost:8082/](http://localhost:8082/)
no more, polling status is now in the monitoring L.A.

2018-10-10 07:48 UTC, laurentleseigneur commented on md/polling.md
> +When a polling execution fails, it can be seen in error on the BICI backend. By default it can be accessed on [http://localhost:8082/](http://localhost:8082/).
no more, polling status is now in the monitoring L.A.

2018-10-10 07:48 UTC, laurentleseigneur commented on md/polling.md
> +More information is available in the output logs on the BICI backend, either in the Standard output or in the log file `logs/bonita-bici.log`
log file is still `logs/bonita-ici.log`

2018-10-10 07:48 UTC, laurentleseigneur commented on md/rest_api.md
> +# REST API
this page has been deleted, replaced by open API version, since swagger is no more documented (may require a rebase)

2018-10-10 07:48 UTC, laurentleseigneur commented on md/security.md
> +REST APIs are not yet secured. In production only Bonita platform and the plaftorm administrator should be able to access the BICI backend by e.g. configuring your network this way.
this is now wrong

2018-10-10 07:50 UTC, laurentleseigneur commented
seems some images are missing in this PR. check http://doc.rd.lan:12037/bici/1.1/ for dead links

2018-10-10 14:09 UTC, laurentleseigneur approved these changes

2018-10-10 16:19 UTC, laurentleseigneur commented
retest this please

2018-10-11 07:46 UTC, NathalieC commented
When you look at the pages in GitHub, the images display fine. I don't get why the deployed PR cannot display the images.

2018-10-12 06:46 UTC, merged